import tkinter as tk
import version as vs

class UiClass:
    def __init__(self) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    def mainloop(self, n: int = 0) -> None: ...
